services:
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      MYSQL_HOST: mariadb
      REDIS_HOST: redis
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/static:/var/www/static:ro
    restart: always
    env_file:
      - .env

  # Bonus
  redis:
    image: redis:inception
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    restart: always
    env_file:
      - .env
  ftp:
    image: ftp:inception
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    restart: always
    env_file:
      - .env
networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  db_data:
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb
