services:
  mariadb:
    image: mariadb:inception
    build: ./requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file:
      - .env

  wordpress:
    image: wordpress:inception
    build: ./requirements/wordpress
    container_name: wordpress
    depends_on:
      mariadb:
        condition: service_started
      redis:
        condition: service_healthy
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:inception
    build: ./requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - inception
    volumes:
      - wordpress_data:/var/www/html
      - ./requirements/nginx/static:/var/www/static:ro
    restart: always
    env_file:
      - .env

  # Bonus
  redis:
    image: redis:inception
    build: ./requirements/bonus/redis
    container_name: redis
    networks:
      - inception
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    env_file:
      - .env
  ftp:
    image: ftp:inception
    build: ./requirements/bonus/ftp
    container_name: ftp
    depends_on:
      - wordpress
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - inception
    ports:
      - "21:21"
      - "10000-10100:10000-10100"
    restart: always
    env_file:
      - .env

  adminer:
    image: adminer:inception
    build: ./requirements/bonus/adminer
    container_name: adminer
    depends_on:
      - mariadb
    networks:
      - inception
    ports:
      - "8080:8080"
    restart: always

  portainer:
    image: portainer:inception
    build: ./requirements/bonus/portainer
    container_name: portainer
    networks:
      - inception
    ports:
      - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always

networks:
  inception:
    driver: bridge

volumes:
  wordpress_data:
  db_data:
  portainer_data:
