events {}

http {
    server {
        listen 443 ssl;
        server_name youbella.42.fr;

        ssl_certificate     /etc/nginx/ssl/nginx.crt;
        ssl_certificate_key /etc/nginx/ssl/nginx.key;
        ssl_protocols TLSv1.2 TLSv1.3;

        root /var/www/html;
        index index.php index.html;

        # 🔥 WordPress routing (IMPORTANT)
        location / {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        # 🔥 PHP handling (IMPORTANT FIX)
        location ~ \.php$ {
            try_files $uri =404;
            include fastcgi_params;
            fastcgi_pass wordpress:9000;
            fastcgi_index index.php;
            fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }

        # 🔥 static files (CSS/JS/images) FIX MIME issue
        location ~* \.(css|js|jpg|jpeg|png|gif|ico|svg)$ {
            try_files $uri =404;
            access_log off;
            expires 30d;
            add_header Content-Type text/css;
        }
    }
}